server:
  port: ${PORT:8080}
  tomcat:
    accesslog:
      enabled: false
    basedir: logs

spring:
  application:
    name: siswa-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:sekolahku}
    username: ${DB_USER:admin}
    password: ${DB_PASS:admin}
    hikari:
      maximum-pool-size: 100
      max-lifetime: 600000
#    tomcat:
#      test-while-idle: true
#      test-on-borrow: true
#      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: app
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        schema_update:
          unique_constraint_strategy: RECREATE_QUIETLY
    show-sql: false

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "Authorization,Link,X-Total-Count"
  allow-credentials: false
  max-age: 1800

#services:
#  guru-service:
#    folder-id: ${GDRIVE_FOLDER_ID:1gAgMcruUptWXDy1gfixFg-EPKosBT5gu}

